- name: Copy ElasticAgent installation file to host
  ansible.windows.win_copy:
    src: ./elastic-agent-7.17.4-windows-x86_64/
    dest: 'C:\elastic-agent\'

- name: Copy CA certificate to host
  ansible.windows.win_copy:
    src: ./ca.crt
    dest: 'C:\elastic-agent\ca.crt'

- name: Install CA certificate in Trusted Root CA Store
  ansible.windows.win_command: certutil -addstore "Root" "C:\elastic-agent\ca.crt"

- name: Install ElasticAgent
  ansible.windows.win_command: C:\elastic-agent\elastic-agent.exe install -f --url=https://172.17.60.50:8220 --enrollment-token=SEtOVHYzOEIwYzJrYk01WUJqYVk6a3NoMWJVQkdUMlcwU3RQRl9yYW5qdw==

- name: Clean up install files
  ansible.windows.win_file:
    path: C:\elastic-agent
    state: absent