- name: Execute Set-Autologon.ps1
  script: files/Set-Autologon.ps1 -username "{{ username }}" -password "ComtechAzure123" -domain "basex"

- name: Reboot after autologon change
  ansible.windows.win_reboot:
    reboot_timeout: 900
    test_command: 'Stop-Computer -WhatIf'
    post_reboot_delay: 30
  retries: 3
  delay: 3
  register: result
  until: result.rebooted

- name: Check logged in user
  ansible.builtin.win_shell: (Get-WMIObject -ClassName Win32_ComputerSystem).Username